package com.swymnation.dms.service;

import com.swymnation.dms.model.ReportData;
import com.swymnation.dms.model.ReportFormat;
import com.swymnation.dms.model.User;
import com.swymnation.dms.model.UserRole;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ReportGeneratorService {

    private final AccessControl accessControl;

    @Autowired
    public ReportGeneratorService(AccessControl accessControl) {
        this.accessControl = accessControl;
    }

    public String exportReport(ReportData data, User user, ReportFormat format) {
        // 1. Security Check [FR-05 SR 4]
        accessControl.enforceAuthorization(user, "Export Report", UserRole.ADMINISTRATOR, UserRole.INSTRUCTOR);

        // 2. Export Logic [FR-05 SR 3]
        String content = "--- " + format + " REPORT ---\n" +
                         "DATA: " + data.getSummary() + "\n" +
                         "RECORDS: " + data.getRecordCount() + "\n" +
                         "GENERATED BY: " + user.getUsername(); // Traceability NFR

        return content;
    }
}